In [8]:
import numpy as np
import pickle
import os

def naive_init_dataset(Ninit, Flist, params, scores):
    
    mf_Xtr_list = []
    mf_ytr_list = []
    mf_Xte_list = []
    mf_yte_list = []

    for fid in Flist:
        buff_X = []
        buff_y = []
        for n in range(Ninit):
            buff_X.append(params[n, :])
            buff_y.append(scores[n, fid])
#             buff_y.append(-scores[n, fid])
        #
        mf_Xtr_list.append(np.array(buff_X))
        mf_ytr_list.append(np.array(buff_y).reshape([-1,1]))
    #

    mfdata = {}
    mfdata['mf_Xtr_list'] = mf_Xtr_list
    mfdata['mf_ytr_list'] = mf_ytr_list
    mfdata['mf_Xte_list'] = mf_Xtr_list
    mfdata['mf_yte_list'] = mf_ytr_list
    
    return mfdata, mf_Xtr_list, mf_ytr_list
#

sobol=False
if sobol:
    prefix = 'sobol_raw_'
else:
    prefix = 'uniform_raw_'

domain='BurgersShock'

pickle_name = os.path.join('buff', domain, prefix+domain+'.pickle')

with open(pickle_name, 'rb') as handle:
    raw = pickle.load(handle)
    
params = raw['X']
scores = raw['Y']

Ninit = 10
Flist = [0,1,2]

mfdata, mf_Xtr_list, mf_ytr_list = naive_init_dataset(Ninit, Flist, params, scores)
        
dump_path = 'preload' 
if not os.path.exists(dump_path):
    os.makedirs(dump_path)
    
dump_fname = domain+'.pickle'
with open(os.path.join(dump_path, dump_fname), 'wb') as handle:
    pickle.dump(mfdata, handle, protocol=pickle.HIGHEST_PROTOCOL)
#

print(np.hstack([mf_ytr_list[0], mf_ytr_list[1], mf_ytr_list[2]]))




[[ 1.56200213e-01  5.46920927e-01  7.05321523e-01]
 [-2.03228475e-04 -2.33221094e-04 -1.91043522e-04]
 [ 6.71339763e-02  1.36365258e-01  3.31743026e-01]
 [-3.63586095e-02  3.96665519e-01  8.75040794e-02]
 [ 5.79390470e-02  2.03722905e-01  3.61763278e-01]
 [ 1.20893633e-01  4.48471987e-01  4.05404022e-01]
 [-1.13235010e-02  3.21324413e-01  1.28809760e+00]
 [-2.62073311e-03 -2.62440954e-03 -2.62220543e-03]
 [ 1.30641998e-01  1.21146236e-01  4.04603886e-01]
 [-1.34256769e-02  3.02437473e-01  3.09430913e-01]]
